#
# See: https://raw.githubusercontent.com/GoogleCloudPlatform/spark-on-k8s-operator/master/examples/spark-pi-prometheus.yaml
#
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: gcs-example-operator
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.4-gcs-prometheus"
  imagePullPolicy: Always
  mainClass: yourMainClass
  mainApplicationFile: "gs://sparknetes/fraud-joiner-assembly-1.1.jar"
  arguments:
    - "gs://fraud-dataset/dataset/bkOn"
    - "gs://sparknetes/fraud.parquet"
  hadoopConf:
    "fs.gs.project.id": "sparknetes"
    "fs.gs.system.bucket": "sparknetes"
    "google.cloud.auth.service.account.enable": "true"
    "google.cloud.auth.service.account.json.keyfile": "/mnt/secrets/key.json"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 2
    memory: "2048m"
    labels:
      version: 2.4.4
      sparknetes: "true"
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    secrets:
      - name: gcloud-creds
        path: /mnt/secrets
        secretType: GCPServiceAccount
    envVars:
      GCS_PROJECT_ID: sparknetes
  executor:
    cores: 2
    instances: 2
    memory: "2048m"
    labels:
      version: 2.4.4
      sparknetes: "true"
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    secrets:
      - name: gcloud-creds
        path: /mnt/secrets
        secretType: GCPServiceAccount
    envVars:
      GCS_PROJECT_ID: sparknetes
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.3.1.jar"
      port: 8090