#
# See: https://raw.githubusercontent.com/GoogleCloudPlatform/spark-on-k8s-operator/master/examples/spark-pi-prometheus.yaml
#
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: gcs-example-operator
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.4-gcs-prometheus"
  imagePullPolicy: Always
  mainClass: yourMainClass
  mainApplicationFile: "https://storage.googleapis.com/sparknetes/fraud-joiner-assembly-1.1.jar"
  arguments:
    - "gs://fraud-dataset/dataset/bkOn"
    - "gs://sparknetes/fraud.parquet"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 2.4.4
      sparknetes: "true"
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    secrets:
      - name: gcloud-creds
        path: /opt/spark/gcp
        secretType: GCPServiceAccount
  executor:
    cores: 2
    instances: 4
    memory: "1024m"
    labels:
      version: 2.4.4
      sparknetes: "true"
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.3.1.jar"
      port: 8090