version: 2
jobs:
  "docker-release":
    docker:
    - image: docker
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout
    - run:
        name: build and publish docker image
        command: |
          docker build -t hypnosapos/dcos-k8s-ml-scaffolds .
          printf 'y' | docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
          docker push hypnosapos/dcos-k8s-ml-scaffolds

workflows:
  version: 2
  build:
    jobs:
    - "docker-release":
        filters:
          branches:
            only: master
