version: 2
jobs:
  docker_build_push:
    docker:
    - image: docker
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Docker login
        command: |
          printf 'y' | docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
    - run:
        name: Install essentials
        command: |
          apk add --no-cache --virtual .build-deps make gcc
    - run:
        name: build and publish sparknetes docker image
        command: |
          make sparknetes-build sparknetes-push
    - run:
        name: build and publish spark docker image
        command: |
          make spark-image

workflows:
  version: 2
  build:
    jobs:
    - docker_build_push:
        filters:
          branches:
            only: master
